[project]
name = "elpis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
]

[tool.uv.workspace]
members = [
    "apps/tracker",
]
